import Header from '@/components/Header';
import Footer from '@/components/Footer';

const services = [
  ['Cleaning Services','Commercial, industrial, medical, apartment, education and food processing cleaning delivered to high professional standards.','#cleaning'],
  ['Waste & Hygiene Services','Waste management and washroom hygiene services that help facilities stay clean, compliant and presentable.','#waste'],
  ['Facilities Management','Trade maintenance, building support, gardening and grounds maintenance for managed sites.','#facilities'],
  ['Supplies & Equipment','Cleaning products, consumables and equipment supply to keep your operation running smoothly.','#supplies']
];
const cleaning = ['Commercial Cleaning','Industrial Cleaning','Health & Medical','Apartment & Housekeeping','Childcare, School and Tertiary Cleaning','Food Processing'];
const facilities = ['Trade Maintenance Services','Building Management','Gardening And Ground Maintenance Services'];

function Section({id,kicker,title,children}){return <section id={id} className="py-20"><div className="container-page"><p className="section-kicker">{kicker}</p><h2 className="text-4xl md:text-5xl font-black text-navy mt-3 mb-8">{title}</h2>{children}</div></section>}

export default function Home(){return <main><Header/>
  <section id="home" className="pt-40 min-h-[760px] bg-gradient-to-br from-navy via-slate-800 to-platinum text-white relative overflow-hidden">
    <div className="absolute inset-0 opacity-20 bg-[radial-gradient(circle_at_20%_20%,white,transparent_25%),radial-gradient(circle_at_90%_10%,#20aeea,transparent_30%),radial-gradient(circle_at_70%_90%,white,transparent_22%)]" />
    <div className="container-page relative grid lg:grid-cols-2 gap-12 items-center py-24">
      <div><p className="uppercase tracking-[.35em] text-skysoft font-bold">PPC · Pure Platinum Cleaning</p><h1 className="text-6xl md:text-7xl font-black leading-tight mt-5">Pure Clean.<br/>Pure Platinum.</h1><p className="text-xl text-white/85 mt-7 max-w-2xl">A multi-disciplined facility management provider delivering commercial cleaning, waste management, hygiene solutions, trade services, gardening, building management and supplies.</p><div className="flex flex-wrap gap-4 mt-10"><a href="#contact" className="btn-primary">Contact Us</a><a href="#services" className="btn-outline">Our Services</a></div></div>
      <div className="card bg-white/95 text-ink"><img src="https://pureplatinumcleaning.com.au/wp-content/uploads/2025/11/fulllogo_transparent_nobuffer.png" alt="Pure Platinum Cleaning" className="w-full max-w-md mx-auto"/><div className="mt-8 grid grid-cols-3 gap-4 text-center"><div><b className="text-3xl text-platinum">24/7</b><p className="text-sm">Support</p></div><div><b className="text-3xl text-platinum">PPC</b><p className="text-sm">Managed</p></div><div><b className="text-3xl text-platinum">VIC</b><p className="text-sm">Service</p></div></div></div>
    </div>
  </section>
  <Section id="services" kicker="Pure Platinum Cleaning" title="Our Services"><div className="grid lg:grid-cols-2 gap-10 items-center"><div className="rounded-[2rem] overflow-hidden shadow-soft bg-slate-100 min-h-[420px]"><img src="https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80" className="w-full h-full object-cover" alt="Professional cleaning"/></div><div><p className="text-lg leading-8 text-slate-600">Pure Platinum Cleaning offers a comprehensive facility management solution, leveraging years of experience to deliver tailored services with exceptional value. Our approach centres on understanding client needs, staying updated with industry advancements, and delivering innovative, effective solutions.</p><div className="grid sm:grid-cols-2 gap-5 mt-8">{services.map(([t,d,h])=><a href={h} key={t} className="card hover:-translate-y-1 transition"><h3 className="font-bold text-xl text-navy">{t}</h3><p className="text-slate-600 mt-3">{d}</p><span className="text-platinum font-bold mt-4 inline-block">Learn More →</span></a>)}</div></div></div></Section>
  <Section id="cleaning" kicker="Cleaning Services" title="Specialist cleaning for every environment"><div className="grid md:grid-cols-3 gap-5">{cleaning.map(x=><div className="card" key={x}><h3 className="text-xl font-bold text-navy">{x}</h3><p className="mt-3 text-slate-600">Reliable, detailed and professionally managed cleaning programs tailored to your facility, operating hours and compliance needs.</p></div>)}</div></Section>
  <section id="waste" className="py-20 bg-slate-50"><div className="container-page grid md:grid-cols-2 gap-8"><div className="card"><p className="section-kicker">Waste and Hygiene Services</p><h2 className="text-4xl font-black text-navy mt-3">Waste Management</h2><p className="text-slate-600 mt-5 leading-8">Structured waste services for offices, commercial premises, industrial locations and managed facilities.</p></div><div className="card"><p className="section-kicker">Washroom & Site Care</p><h2 className="text-4xl font-black text-navy mt-3">Hygiene Services</h2><p className="text-slate-600 mt-5 leading-8">Hygiene programs designed to keep bathrooms, shared spaces and public-facing facilities clean, stocked and professional.</p></div></div></section>
  <Section id="facilities" kicker="Facilities Management" title="Integrated facility support"><div className="grid md:grid-cols-3 gap-5">{facilities.map(x=><div className="card" key={x}><h3 className="text-xl font-bold text-navy">{x}</h3><p className="mt-3 text-slate-600">Dependable support services delivered with responsive management and attention to presentation.</p></div>)}</div></Section>
  <section id="supplies" className="py-20 bg-gradient-to-br from-platinum to-skysoft text-white"><div className="container-page grid md:grid-cols-2 gap-8"><div><p className="uppercase tracking-[.25em] font-bold">Supplies</p><h2 className="text-5xl font-black mt-3">Products and Equipment</h2><p className="text-white/90 mt-6 leading-8">Cleaning products, consumables and equipment for commercial sites, managed properties and operational teams.</p></div><div className="grid gap-5"><div className="bg-white/20 rounded-3xl p-7"><h3 className="text-2xl font-bold">Cleaning Products and Supplies</h3></div><div className="bg-white/20 rounded-3xl p-7"><h3 className="text-2xl font-bold">Cleaning Equipment</h3></div></div></div></section>
  <Section id="about" kicker="About PPC" title="Experience, reliability and client focus"><p className="max-w-4xl text-xl text-slate-600 leading-9">As a multi-disciplined service provider, PPC is known for expertise, reliability and commitment to exceeding client expectations. We deliver competitive services while maintaining high standards of client satisfaction.</p></Section>
  <section id="contact" className="py-20 bg-slate-50"><div className="container-page grid lg:grid-cols-2 gap-10"><div><p className="section-kicker">Contact Us</p><h2 className="text-5xl font-black text-navy mt-3">Talk to Pure Platinum Cleaning</h2><p className="text-slate-600 mt-6">Call <b>+613 9908 3240</b> or email <b>clean@pureplatinumcleaning.com.au</b>.</p></div><form className="card grid gap-4"><input className="rounded-xl border p-4" placeholder="First Name"/><input className="rounded-xl border p-4" placeholder="Last Name"/><input className="rounded-xl border p-4" placeholder="Email"/><textarea className="rounded-xl border p-4" rows="5" placeholder="How can we help?"/><button className="btn-primary" type="button">Submit Enquiry</button></form></div></section>
  <Footer/>
</main>}
